serviceType: NodePort
service:
  nodePorts:
    http: "30305"
    https: "30443"
dashboard:
  enabled: true
  domain: traefik.apps.ocp-gc.snamretegas.priv 
rbac:
  enabled: true
ssl:
  enabled: true
  #enforced: true 
  #upstream: true
  #insecureSkipVerify: false
  tlsMinVersion: VersionTLS12
